# Generated by Django 5.0.3 on 2024-04-05 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajofinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=39526312, on_delete=django.db.models.deletion.CASCADE, to='trabajofinal.proveedor'),
            preserve_default=False,
        ),
    ]
